// Homepage Manager — CMS-side schema mirroring the public homepage sections
// (E-04 through E-15). Each section carries editable fields, feature slots,
// and an enabled flag. Ready to be swapped for a real DB collection later.

import { IMG } from '@/lib/content/homepage'

export const HOMEPAGE_SECTIONS = [
  {
    id: 'hero-video',
    label: 'Hero Video',
    kind: 'hero',
    description: 'Full-viewport cinematic hero with background video and primary CTA.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'Kota Bekasi · West Java · Indonesia' },
      { key: 'title',     label: 'Main title',  type: 'textarea', value: 'Where Heritage Meets the Smart City' },
      { key: 'subtitle',  label: 'Subtitle',    type: 'textarea', value: 'From centuries-old klenteng to floating skylines—discover a city rewriting its own story.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text',     value: 'Explore Bekasi' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link',     value: '/discover' },
      { key: 'videoUrl',  label: 'Background media', type: 'media', value: IMG.floatingCity },
    ],
  },
  {
    id: 'quick-explore',
    label: 'Quick Explore',
    kind: 'grid',
    description: 'Four theme entry tiles (Heritage, Urban, Culinary, Nature).',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'Start Here' },
      { key: 'title',     label: 'Section title', type: 'text',   value: 'Four ways into Bekasi.' },
      { key: 'subtitle',  label: 'Section subtitle', type: 'textarea', value: 'Pick a theme—we’ll take you into the neighborhoods that live it best.' },
    ],
    featured: { type: 'destinations', slots: 4, ids: ['hok-lay-kiong', 'floating-smart-city', 'kampung-bali-harapan-jaya', 'situ-rawa-gede'] },
  },
  {
    id: 'floating-city-signature',
    label: 'Floating City Signature',
    kind: 'signature',
    description: 'Signature architectural showcase with parallax and floating cutout.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'City Signature' },
      { key: 'title',     label: 'Title',       type: 'textarea', value: 'The floating skyline of Kota Bekasi.' },
      { key: 'kickerImage', label: 'Signature image', type: 'media', value: IMG.floatingCityCutout },
      { key: 'backgroundImage', label: 'Background', type: 'media', value: IMG.floatingCityBg },
    ],
  },
  {
    id: 'featured-icons',
    label: 'Featured Icons of Bekasi',
    kind: 'carousel',
    description: 'Horizontal carousel of iconic destinations — embla-powered.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'Featured Icons' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'The icons of Bekasi.' },
    ],
    featured: { type: 'destinations', slots: 6, ids: ['hok-lay-kiong', 'gedung-juang-45', 'kampung-adat-kranggan', 'floating-smart-city', 'piramida-terbalik-summarecon', 'stadion-patriot-candrabhaga'] },
  },
  {
    id: 'heritage-culture',
    label: 'Heritage & Culture Spotlight',
    kind: 'spotlight',
    description: 'Editorial spotlight on Bekasi heritage sites.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'Heritage & Culture' },
      { key: 'title',     label: 'Title',       type: 'textarea', value: 'A living memory of the city.' },
      { key: 'subtitle',  label: 'Subtitle',    type: 'textarea', value: 'Not preserved—practiced. Ritual, temple, kampung, and craft, still in daily use.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text',     value: 'Explore heritage' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link',     value: '/discover/heritage' },
    ],
    featured: { type: 'destinations', slots: 3, ids: ['hok-lay-kiong', 'kampung-adat-kranggan', 'gedung-juang-45'] },
  },
  {
    id: 'urban-lifestyle',
    label: 'Urban Lifestyle',
    kind: 'slider',
    description: 'Reel of modern lifestyle spots — rooftops, malls, night culture.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'Urban Lifestyle' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'A city that stays up.' },
    ],
    featured: { type: 'destinations', slots: 5, ids: ['summarecon-mall-bekasi', 'piramida-terbalik-summarecon', 'skywalk-summarecon', 'rooftop-cinema-bekasi', 'pakuwon-mall-bekasi'] },
  },
  {
    id: 'city-pulse',
    label: 'City Pulse (Events Ticker)',
    kind: 'ticker',
    description: 'Live-events ticker with 3–6 upcoming events.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'City Pulse' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'What’s happening this week.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text', value: 'See all events' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link', value: '/events' },
    ],
    featured: { type: 'events', slots: 4, ids: ['bekasi-cultural-festival-2026', 'skyline-sunset-rooftop-series', 'bekasi-food-fair-vol-8', 'weekend-book-bazaar'] },
  },
  {
    id: 'utility-panel',
    label: 'Food, Stay & Access',
    kind: 'utility',
    description: 'Three-column utility panel: Food, Stay, Getting Around.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'Practical' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'Everything you’ll need on the ground.' },
    ],
  },
  {
    id: 'planner-intro',
    label: 'Smart Planner Intro',
    kind: 'planner',
    description: 'Introduction to the AI Smart Planner with interactive mock.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'Smart Trip Planner' },
      { key: 'title',     label: 'Title',       type: 'textarea', value: 'Let AI plan your Bekasi day.' },
      { key: 'subtitle',  label: 'Subtitle',    type: 'textarea', value: 'Tell us your interests—we’ll thread destinations, food, and transit into one itinerary.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text',     value: 'Open Smart Planner' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link',     value: '/planner' },
    ],
  },
  {
    id: 'map-preview',
    label: 'Explore Map Preview',
    kind: 'map',
    description: 'Interactive canvas preview of the Explore Map.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text',     value: 'Explore Map' },
      { key: 'title',     label: 'Title',       type: 'textarea', value: 'Every place, on one canvas.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text',     value: 'Open Explore Map' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link',     value: '/map' },
    ],
  },
  {
    id: 'stories-from-bekasi',
    label: 'Stories from Bekasi',
    kind: 'stories',
    description: 'Editorial teaser — 3 latest long-form stories.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'City Stories' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'Read the city slowly.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text', value: 'Open the Journal' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link', value: '/stories' },
    ],
    featured: { type: 'stories', slots: 3, ids: ['return-of-kranggan-ritual', 'the-city-that-eats-standing-up', 'a-skyline-in-motion'] },
  },
  {
    id: 'latest-blog',
    label: 'Latest from Blog',
    kind: 'blog',
    description: 'Grid of 3–4 recent blog posts.',
    enabled: true,
    fields: [
      { key: 'kicker',    label: 'Kicker',      type: 'text', value: 'BekasiGo Blog' },
      { key: 'title',     label: 'Section title', type: 'text', value: 'Fresh from the desk.' },
      { key: 'ctaLabel',  label: 'CTA label',   type: 'text', value: 'All posts' },
      { key: 'ctaHref',   label: 'CTA link',    type: 'link', value: '/blog' },
    ],
    featured: { type: 'blog', slots: 4, ids: ['the-perfect-weekend-in-bekasi-48-hour-guide', 'lrt-jabodebek-latest-schedule-and-tips', 'new-cafe-openings-in-bekasi-june-2026', 'ramadan-in-bekasi-timings-and-events-2026'] },
  },
]

export const SECTION_KIND_META = {
  hero:      { label: 'Hero',       color: '#0B3D3A' },
  grid:      { label: 'Grid',        color: '#155F58' },
  signature: { label: 'Signature',    color: '#B48A2D' },
  carousel:  { label: 'Carousel',    color: '#1E7A72' },
  spotlight: { label: 'Spotlight',    color: '#A34E2B' },
  slider:    { label: 'Slider',      color: '#3F9186' },
  ticker:    { label: 'Ticker',      color: '#E27D5A' },
  utility:   { label: 'Utility',     color: '#8C6A20' },
  planner:   { label: 'Planner',     color: '#124F4A' },
  map:       { label: 'Map',         color: '#155F58' },
  stories:   { label: 'Stories',     color: '#B48A2D' },
  blog:      { label: 'Blog',        color: '#1E7A72' },
}
